### PR TITLE
[Closes #28] Take the second element from custom token tuple

### LINKED ISSUE #28: When aleppo:process_tree/3 catches an exception the token added is not a valid Erlang token

### PR DESCRIPTION
**Pull request by jfacorro**
#28

### CODE REVIEW

File: src/aleppo.erl [hunk 1]
```diff
@@ -190,6 +190,8 @@ process_tree([Node|Rest], TokenAcc, Context) ->
         end
     catch
         _:_ ->
+            %% Get the actual token by unboxing it from aleppo's custom token
+            ActualToken = erlang:element(2, Node),
```
Comment (gadgetci) [inline src/aleppo.erl]: According to **Compiler**:
> Warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)

Comment (gadgetci) [inline src/aleppo.erl]: According to **Compiler**:
> Warning: variable 'ActualToken' is unused
